#theme: jekyll-theme-slate
theme: jekyll-theme-cayman
title: [Let's make it Pope-litical!]
description: [Investigation of the Pope’s political position]
#navbar-img: "/data/popefrancis.png"
#cover-img: "/data/popefrancis.png"
